CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "locations" (
    "ID"      UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    "name"          VARCHAR(255) NOT NULL UNIQUE,
    "code"          VARCHAR(50) NOT NULL UNIQUE,
    "createdAtUTC"    TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    "lastUpdatedAtUTC"  TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
